addr: "127.0.0.1:9379"

etcd:
  addrs:
    - "127.0.0.1:2379"
  username:
  password:
  tls:
    enable: false
    cert_file:
    key_file:
    ca_file:

controller:
  failOver:
    GCInterval: 1
    pingInterval: 6
    maxPingCount: 2
    minAliveSize: 10
    MaxFailureRatio: 0.8
